=== sermo-de-arboribus/EBP-testdata-generator/src/testdatagen/config/quotes-schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="xml.xsd"/>
  <xs:element name="quotes">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="quote"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="quote">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="version"/>
        <xs:element ref="author" maxOccurs="5"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="version">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="text"/>
        <xs:element ref="source"/>
      </xs:sequence>
      <xs:attribute name="status" use="required">
        <xs:simpleType>
          <xs:list>
            <xs:simpleType>
              <xs:restriction base="xs:string">
                <xs:enumeration value="original" />
                <xs:enumeration value="translation" />
                <xs:enumeration value="unpublished" />
              </xs:restriction>
            </xs:simpleType>
          </xs:list>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute ref="xml:lang" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="text">
    <xs:complexType mixed="true">
      <xs:sequence>
        <xs:element name="em" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="source">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="title"/>
        <xs:element ref="idref" minOccurs="0"/>
        <xs:element ref="page" minOccurs="0"/>
        <xs:element ref="translator" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="idref" type="xs:integer"/>
  <xs:element name="page">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:pattern value="([-0-9/]+)|(check)|([IVXLMC]+)"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="title" type="xs:string"/>
  <xs:element name="author" type="xs:string"/>
  <xs:element name="translator" type="xs:string"/>
</xs:schema>

=== sermo-de-arboribus/EBP-testdata-generator/src/testdatagen/config/chapterSentences.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="quotes.css"?>
<quotes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="quotes-schema.xsd">
    <quote>
        <version xml:lang="fr-FR" status="original">
            <text>Une œuvre où il y a des théories est comme un objet sur lequel on laisse la marque du prix.</text>
            <source>
                <title>A la recherche du temps perdu</title>
            </source>
        </version>
        <version xml:lang="de-DE" status="translation">
            <text>Ein Buch, das Theorien enthält, ist wie ein Gegenstand, an dem noch das Preisschild hängt.</text>
            <source>
                <title>Auf der Suche nach der verlorenen Zeit</title>
                <idref>2409</idref>
                <page>check</page>
            </source>
        </version>
        <version xml:lang="en-US" status="translation">
            <text>A work in which there are theories is like an object which still has its price-tag
                on it.</text>
            <source>
                <title>In Search of Lost Time</title>
            </source>
        </version>
        <author>Proust, Marcel</author>
    </quote>
    <quote>
        <version xml:lang="de-DE" status="translation">
            <text>Wenn Sie sich an ihre Berufserfahrung hielten statt an Ihr scheußliches Credo 'Selbst ist der Mann', dann wüßten Sie, daß der Glaube an sich selbst zu den gängigsten Merkmalen eines maroden Menschen gehört.</text>
            <source>
                <title>Orthodoxie</title>
                <idref>563</idref>
                <page>38</page>
            </source>
        </version>
        <version xml:lang="en-GB" status="original">
            <text>If you consulted your business experience instead of your ugly individualistic philosophy, you would know that believing in himself is one of the commonest signs of a rotter.</text>
            <source>
                <title>Heretics / Orthodoxy</title>
                <idref>560</idref>
                <page>176</page>
            </source>
        </version>
        <author>Chesterton, Gilbert Keith</author>
    </quote>
    <quote>
        <version xml:lang="de-DE" status="original">
            <text>Sogar der Spartakist Seebacher erkannte das korrekte Verhalten des Königs an und meinte zur Notwendigkeit, die Monarchie abzuschaffen, nur: "S'ischt halt wegge dem Sischteem".</text>
            <source>
                <title>Vier Zeiten</title>
                <idref>3172</idref>
                <page>17</page>
            </source>         
        </version>
        <author>Weizsäcker, Richard von</author>
    </quote>
    <quote>
        <version xml:lang="de-DE" status="translation">
            <text>Tatsache ist leider, daß die Günstlinge des Himmels, die Zivilisatoren der Welt - die <em>race blanche</em> [...] - von Natur aus die intolerantesten Menschen sind.</text>
            <source>
                <title>Meine sieben Kriege</title>
                <idref>2545</idref>
                <page>153</page>
            </source>
        </version>
        <version status="original" xml:lang="en-GB">
            <text>The fact is, I fear that the favourites of heaven - the civilizers of the world - la <em>race blanche</em> of my friend the doctor, are naturally the most intolerant in the world.</text>
            <source>
                <title>My Diary in India, in the Year 1858-59</title>
            </source>
        </version>
        <author>Russell, William Howard</author>
    </quote>
    <quote>
        <version xml:lang="de-DE" status="translation">
            <text>Geniale Ideen hat man beim Dösen in einem Vorstadtgarten - oder am Schreibtisch.</text>
            <source>
                <title>Darwins Schatten</title>
                <idref>2509</idref>
            </source>
        </version>
        <version status="original" xml:lang="en-GB">
            <text>The story that Darwin had the idea for evolution during the voyage of the <em>Beagle</em>, particularly on the Galapagos Islands, is a myth. Great ideas instead come while napping in suburban gardens or in studies.</text>
            <source>
                <title>Darwin's Spectre: Evolutionary Biology in the Modern World</title>
            </source>
        </version>
        <author>Rose, Michael R.</author>
    </quote>
    <quote>
        <version status="original" xml:lang="en-US">
            <text>Grown-ups keep their feet on the ground when they swing. I hate that.</text>
            <source>
                <title>Fuel</title>
                <idref>2285</idref>
                <page>31</page>
            </source>
        </version>
        <author>Nye, Naomi Shihab</author>
    </quote>
    <quote>
        <version status="original" xml:lang="en-GB">
            <text>And though St. John the Evangelist saw many strange monsters in his vision, he saw no creature so wild as one of his own commentators.</text>
            <source>
                <title>Heretics / Orthodoxy</title>
                <idref>560</idref>
                <page>178</page>                
            </source>
        </version>
        <version status="translation" xml:lang="de-DE">
            <text>Und obwohl der Evangelist Johannes in seinen Visionen viele seltsame Ungeheuer erblickte, sah er doch kein Geschöpf, das so irrsinnig war wie manch einer seiner Kommentatoren.</text>
            <source>
                <title>Orthodoxie</title>
                <idref>563</idref>
                <page>44</page>
            </source>
        </version>
        <author>Chesterton, Gilbert Keith</author>
    </quote>
    <quote>
        <version status="translation" xml:lang="de-DE">
            <text>Aber die Grundlage des menschlichen Seelenfriedens und des halbwegs erträglichen Zusammenlebens ist eine sanfte Isolierschicht von Stumpfsinn, ohne die unsere Nerven fortwährend aufgerieben würden...</text>
            <source>
                <title>Lucilla</title>
                <idref>590</idref>
            </source>
        </version>
        <author>Collins, Wilkie</author>
    </quote>
    <quote>
        <version status="original" xml:lang="grc">
            <text>εύναὶ δὲ παράτροποι ές κακότατ᾽ άθρόαν ἔβαλόν ποτε καὶ τὸν ἵκοντ᾽.</text>
            <source>
                <title>Pythia II.</title>
            </source>
        </version>
        <version status="translation" xml:lang="de-DE">
            <text>Abartige Bettgemeinschaft ließ oft schon in dichtgedrängtes Unglück fallen. (Übers. Dieter Bremer)</text>
            <source>
                <title>Siegeslieder. Griechisch-deutsch.</title>
                <idref>2375</idref>
            </source>
        </version>
        <version status="translation" xml:lang="de-DE">
            <text>Frevelnde Liebesgemeinschaft stürzt' oft auch gelingend ins Elend. (Übers. Wilhelm v. Humboldt)</text>
            <source>
                <title>Wilhelm von Humboldt's gesammelte werke, Band 2 (1841)</title>
                <page>293</page>
            </source>
        </version>
        <author>Pindar</author>
    </quote>
    <quote>
        <version status="original" xml:lang="de-DE">
            <text>&#8222;Wie kann ein Wohltäter der Menschen, mit der höchsten Weisheit und Gnade begabt, solch ein Saumatz sein!" seufzte Frau Hildegard, Aber Berthold, der viel in Römern und Griechen gelesen hatte, suchte ihr deutlich zu machen, wie gerade die allgemeine, wissenschaftliche Ansicht, wenn sie allein herrschend würde, die sittlichen Grenzen des einzelnen Menschen auslösche; er sehe so Mannigfaltiges, Widersprechendes geglaubt und geehrt, daß er nur den Geist achte, in welchem alles getrieben würde. Frau Hildegard schüttelte mit dem Kopfe und warnte Berthold gegen die Bücher, daß er es nicht auch einmal so treibe wie Faust, wenn er ganz gesund würde.</text>
            <source>
                <title>Die Kronenwächter</title>
                <page>613</page>
            </source>
        </version>
        <author>Arnim, Achim von</author>
    </quote>
    <quote>
        <version xml:lang="de-DE" status="translation">
            <text>Der Dichter will nichts weiter als seinen Kopf in den Himmel zu stecken. Der Logiker sucht den Himmel in seinen Kopf zu stecken. Und dabei platzt ihm sein Kopf.</text>
            <source>
                <title>Orthodoxie</title>
                <idref>563</idref>
                <page>44</page>
            </source>
        </version>
        <version xml:lang="en-GB" status="original">
            <text>The poet only asks to get his head into the heavens. It is the logician who seeks to get the heavens into his head. And it is his head that splits.</text>
            <source>
                <title>Heretics / Orthodoxy</title>
                <idref>560</idref>
                <page>178</page>
            </source>
        </version>
        <author>Chesterton, Gilbert Keith</author>
    </quote>
    <quote>
        <version status="original" xml:lang="de-CH">
            <text>Jeder Mensch erfindet sich früher oder später eine Geschichte, die er für sein Leben hält.</text>
            <source>
                <title>Mein Name sei Gantenbein</title>
                <idref>970</idref>
                <page>58</page>
            </source>
        </version>
        <version status="translation" xml:lang="en-US">
            <text>Sooner or later everyone invents for himself a story which he regards as his life.</text>
            <source>
                <title>Gantenbein (Methuen, 1982)</title>
                <page>47</page>
            </source>
        </version>
        <version status="translation" xml:lang="fr-FR">
            <text>Tout homme, dit-il, s'invente tôt ou tard une histoire qu'il prend pour sa vie.</text>
            <source>
                <title>Le désert des miroirs</title>
